"use client";

import React, { useState } from "react";
import { 
  Check, 
  RotateCcw, 
  Info,
  ArrowRight,
  Plus,
  Trash2,
  Edit2,
  CheckCircle2,
  X
} from "lucide-react";

export interface EquipmentConfig {
  id: string;
  name: string;
  category: "feed" | "desulfurization" | "saturation" | "smr" | "convection" | "cooling";
  description: string;
  enabled: boolean;
  required?: boolean;
  isCustom?: boolean;
  // Sub-configuration attributes
  numExchangers?: number;
  arrangement?: "Series" | "Parallel";
  stages?: number;
  driverType?: "Steam Turbine" | "Electric Motor";
  adsorberArrangement?: "Lead-Lag Dual Bed" | "Single Bed";
  tubes?: number;
  firingType?: "Top-Fired" | "Side-Fired";
  processStream?: string;
  passNumber?: number;
}

export const INITIAL_EQUIPMENT: EquipmentConfig[] = [
  // Zone 1: Feed Prep & Compression
  {
    id: "feed_ko_drum",
    name: "Natural Gas Knockout Drum",
    category: "feed",
    description: "Separates pipeline liquids prior to compression.",
    enabled: true,
    processStream: "Raw Natural Gas"
  },
  {
    id: "feed_preheater",
    name: "Feed Gas Preheater",
    category: "feed",
    description: "Preheats incoming raw natural gas to optimal temperature.",
    enabled: true,
    numExchangers: 2,
    arrangement: "Series",
    processStream: "Raw Natural Gas"
  },
  {
    id: "feed_compressor",
    name: "Natural Gas Feed Compressor",
    category: "feed",
    description: "Multi-stage compressor elevating feed gas pressure.",
    enabled: true,
    stages: 2,
    driverType: "Electric Motor",
    processStream: "Compressed Natural Gas"
  },
  {
    id: "feed_cooler",
    name: "Feed Gas Aftercooler",
    category: "feed",
    description: "Removes compression heat to establish steady inlet temperature.",
    enabled: true,
    numExchangers: 1,
    arrangement: "Parallel",
    processStream: "Cooled Feed Gas"
  },

  // Zone 2: Desulfurization & Purification
  {
    id: "hds_reactor",
    name: "HDS Hydrogenation Reactor",
    category: "desulfurization",
    description: "Converts organic sulfur compounds into hydrogen sulfide.",
    enabled: true,
    processStream: "Hydrotreated Gas"
  },
  {
    id: "zno_adsorbers",
    name: "Zinc Oxide Sulfur Adsorbers",
    category: "desulfurization",
    description: "Dual-bed zinc oxide guard vessels polishing sulfur below 0.05 ppm.",
    enabled: true,
    required: true,
    adsorberArrangement: "Lead-Lag Dual Bed",
    processStream: "Sweet Natural Gas"
  },

  // Zone 3: Saturation & Steam Addition
  {
    id: "saturator_column",
    name: "Natural Gas Saturator Column",
    category: "saturation",
    description: "Direct contact tower saturating gas with hot water.",
    enabled: true,
    processStream: "Saturated Gas & Hot Water"
  },
  {
    id: "saturator_pumps",
    name: "Saturator Circulation Pumps",
    category: "saturation",
    description: "Continuous circulation pumps supplying wash water.",
    enabled: true,
    processStream: "Saturator Circulation Water"
  },
  {
    id: "saturator_exchanger",
    name: "Saturator Water Heat Exchanger",
    category: "saturation",
    description: "Recovers waste heat to re-heat circulation water.",
    enabled: true,
    numExchangers: 2,
    arrangement: "Series",
    processStream: "Hot Saturator Water"
  },
  {
    id: "steam_mixer",
    name: "Direct Steam Injection Mixer",
    category: "saturation",
    description: "Trims steam injection to balance exact S/C ratio.",
    enabled: true,
    required: true,
    processStream: "HP Steam + Saturated Gas"
  },

  // Zone 4: Primary Reformer (SMR) Radiant Box
  {
    id: "smr_radiant_box",
    name: "Primary Reformer (SMR) Radiant Box",
    category: "smr",
    description: "Radiant furnace housing catalyst tubes for endothermic reforming.",
    enabled: true,
    required: true,
    firingType: "Top-Fired",
    tubes: 480,
    processStream: "Mixed Gas & Steam -> Syngas"
  },

  // Zone 5: Convection Section Waste Heat Recovery Coils
  {
    id: "conv_coil_1",
    name: "High-Temp Process Preheater Coil (Pass 1)",
    category: "convection",
    description: "Recovers high-temperature flue gas heat above arch.",
    enabled: true,
    passNumber: 1,
    processStream: "Natural Gas + Steam Preheat"
  },
  {
    id: "conv_coil_2",
    name: "Mixed Feed Preheater Coil (Pass 2)",
    category: "convection",
    description: "Preheats mixed gas/steam before radiant box.",
    enabled: true,
    passNumber: 2,
    processStream: "Mixed Feed Gas"
  },
  {
    id: "conv_coil_3",
    name: "HP Steam Superheater Coil (Pass 3)",
    category: "convection",
    description: "Superheats steam generated by the waste heat boiler.",
    enabled: true,
    passNumber: 3,
    processStream: "HP Saturated -> Superheated Steam"
  },
  {
    id: "conv_coil_4",
    name: "Combustion Air Preheater Coil (Pass 4)",
    category: "convection",
    description: "Preheats combustion air using flue gas.",
    enabled: true,
    numExchangers: 1,
    arrangement: "Series",
    passNumber: 4,
    processStream: "Combustion Air"
  },
  {
    id: "id_fan",
    name: "Induced Draft (ID) Fan",
    category: "convection",
    description: "Maintains negative furnace arch draft pressure.",
    enabled: true,
    driverType: "Steam Turbine",
    processStream: "Exhaust Flue Gas"
  },
  {
    id: "fd_fan",
    name: "Forced Draft (FD) Fan",
    category: "convection",
    description: "Pressurizes fresh atmospheric combustion air.",
    enabled: true,
    driverType: "Electric Motor",
    processStream: "Fresh Atmospheric Air"
  },
  {
    id: "flue_stack",
    name: "Flue Gas Exhaust Stack",
    category: "convection",
    description: "Chimney venting cooled flue gas with virtual PEMS.",
    enabled: true,
    required: true,
    processStream: "Cooled Flue Gas to Atmosphere"
  },

  // Zone 6: Reformed Syngas Cooling & Steam Generation
  {
    id: "waste_heat_boiler",
    name: "Waste Heat Boiler (WHB)",
    category: "cooling",
    description: "Rapidly quenches syngas to generate HP steam.",
    enabled: true,
    required: true,
    processStream: "Hot Syngas Quench (856°C -> 360°C)"
  },
  {
    id: "steam_drum",
    name: "High-Pressure Steam Drum",
    category: "cooling",
    description: "Separates steam-water mixture with risers and downcomers.",
    enabled: true,
    processStream: "HP Steam-Water Separation"
  },
  {
    id: "syngas_cooler",
    name: "Reformed Syngas Process Cooler",
    category: "cooling",
    description: "Cools syngas to ambient separation temperature.",
    enabled: true,
    numExchangers: 2,
    arrangement: "Series",
    processStream: "Cooled Syngas (360°C -> 38°C)"
  },
  {
    id: "condensate_separator",
    name: "Process Condensate Separator Drum",
    category: "cooling",
    description: "Knocks out condensed water before syngas compression.",
    enabled: true,
    processStream: "Raw Syngas + Process Condensate"
  }
];

export const ZONE_TABS = [
  { key: "feed", num: 1, label: "Feed Gas & Compression" },
  { key: "desulfurization", num: 2, label: "Desulfurization & Guard" },
  { key: "saturation", num: 3, label: "Saturation & Steam Loop" },
  { key: "smr", num: 4, label: "Primary Reformer Furnace" },
  { key: "convection", num: 5, label: "Convection Heat Recovery" },
  { key: "cooling", num: 6, label: "Reformed Syngas Cooling" }
] as const;

interface EquipmentQuestionnaireProps {
  equipment: EquipmentConfig[];
  activeTab: string;
  onSelectTab: (tabKey: string) => void;
  onToggle: (id: string, enabled: boolean) => void;
  onUpdateSubOption: (id: string, field: string, value: any) => void;
  onUpdateName?: (id: string, newName: string) => void;
  onUpdateDescription?: (id: string, newDesc: string) => void;
  onAddEquipment?: (item: EquipmentConfig) => void;
  onDeleteEquipment?: (id: string) => void;
  onReset: () => void;
  onSelectAll: () => void;
  onDeselectNonRequired: () => void;
  onNextStep: () => void;
  activeKpiCount?: number;
}

export const EquipmentQuestionnaire: React.FC<EquipmentQuestionnaireProps> = ({
  equipment,
  activeTab,
  onSelectTab,
  onToggle,
  onUpdateSubOption,
  onUpdateName,
  onUpdateDescription,
  onAddEquipment,
  onDeleteEquipment,
  onReset,
  onSelectAll,
  onDeselectNonRequired,
  onNextStep,
  activeKpiCount = 12
}) => {
  const currentZoneMeta = ZONE_TABS.find(t => t.key === activeTab) || ZONE_TABS[0];
  const itemsInCurrentZone = equipment.filter(e => e.category === activeTab);
  const activeInZone = itemsInCurrentZone.filter(i => i.enabled).length;

  // Inline editing state for equipment names
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editNameValue, setEditNameValue] = useState<string>("");
  const [editStreamValue, setEditStreamValue] = useState<string>("");

  // New Convection Exchanger form modal/inline state
  const [isAddingCoil, setIsAddingCoil] = useState<boolean>(false);
  const [newCoilName, setNewCoilName] = useState<string>("");
  const [newCoilStream, setNewCoilStream] = useState<string>("Boiler Feed Water (BFW)");
  const [newCoilPass, setNewCoilPass] = useState<number>(5);
  const [newCoilShells, setNewCoilShells] = useState<number>(1);
  const [newCoilArrangement, setNewCoilArrangement] = useState<"Series" | "Parallel">("Series");

  const startEditing = (eq: EquipmentConfig) => {
    setEditingId(eq.id);
    setEditNameValue(eq.name);
    setEditStreamValue(eq.processStream || eq.description);
  };

  const saveEditing = (id: string) => {
    if (editNameValue.trim() && onUpdateName) {
      onUpdateName(id, editNameValue.trim());
    }
    if (editStreamValue.trim() && onUpdateDescription) {
      onUpdateDescription(id, editStreamValue.trim());
    }
    setEditingId(null);
  };

  const handleCreateConvectionCoil = () => {
    if (!newCoilName.trim()) return;
    const newId = `conv_coil_custom_${Date.now()}`;
    const newCoil: EquipmentConfig = {
      id: newId,
      name: newCoilName.trim(),
      category: "convection",
      description: `Additional Convection Coil (${newCoilStream}).`,
      enabled: true,
      isCustom: true,
      passNumber: newCoilPass,
      processStream: newCoilStream,
      numExchangers: newCoilShells,
      arrangement: newCoilArrangement
    };
    if (onAddEquipment) {
      onAddEquipment(newCoil);
    }
    setIsAddingCoil(false);
    setNewCoilName("");
    setNewCoilPass(prev => prev + 1);
  };

  return (
    <div className="flex flex-col h-full bg-white rounded-lg border border-slate-200 shadow-xs overflow-hidden select-none text-slate-800 font-sans">
      {/* Header Banner - Crisp Rectangular Blue */}
      <div className="bg-[#0090d0] px-3.5 py-2 text-white flex items-center justify-between shrink-0 shadow-2xs">
        <div className="flex items-center gap-2">
          <h2 className="text-xs font-semibold uppercase tracking-wider text-white">
            {currentZoneMeta.label}
          </h2>
          <span className="text-[9.5px] font-mono font-bold px-2 py-0.5 rounded-xs bg-white/20 text-white border border-white/30">
            {activeInZone}/{itemsInCurrentZone.length} Active
          </span>
        </div>

        <div className="flex items-center gap-1.5">
          {activeTab === "convection" && (
            <button
              type="button"
              onClick={() => setIsAddingCoil(true)}
              className="text-[10px] font-medium px-2 py-0.5 rounded bg-emerald-600 hover:bg-emerald-700 text-white border border-emerald-500 transition-all flex items-center gap-1 cursor-pointer shadow-2xs"
            >
              <Plus className="w-3 h-3" />
              <span>Add Exchanger</span>
            </button>
          )}

          <button
            type="button"
            onClick={onReset}
            className="text-[10px] font-normal px-2 py-0.5 rounded bg-white/15 hover:bg-white/25 text-white border border-white/30 transition-all flex items-center gap-1 cursor-pointer"
          >
            <RotateCcw className="w-2.5 h-2.5" />
            Defaults
          </button>
          <button
            type="button"
            onClick={onSelectAll}
            className="text-[10px] font-normal px-2 py-0.5 rounded bg-white text-[#0090d0] hover:bg-slate-50 transition-all flex items-center gap-1 cursor-pointer"
          >
            <Check className="w-2.5 h-2.5" />
            All
          </button>
        </div>
      </div>

      {/* Sub-bar with selection guidance */}
      <div className="bg-slate-50 px-3.5 py-1.5 border-b border-slate-200 flex items-center justify-between text-[11px] text-slate-600">
        <div className="flex items-center gap-1.5">
          <span className="font-medium text-slate-700">Section {currentZoneMeta.num} of 6:</span>
          <span className="font-normal text-slate-500">Blue = Active in PFD • White = Excluded • Click pencil to edit equipment name</span>
        </div>
        <button
          type="button"
          onClick={onDeselectNonRequired}
          className="font-medium text-slate-500 hover:text-slate-800 underline underline-offset-2 cursor-pointer"
        >
          Core Only
        </button>
      </div>

      {/* Inline Form to Add Additional Convection Exchanger */}
      {isAddingCoil && activeTab === "convection" && (
        <div className="p-3 bg-sky-50/70 border-b border-sky-200 animate-fadeIn">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-medium text-slate-800 flex items-center gap-1.5">
              <Plus className="w-3.5 h-3.5 text-[#0090d0]" />
              Add Additional Convection Exchanger / Coil (Pass {newCoilPass}+)
            </span>
            <button 
              type="button" 
              onClick={() => setIsAddingCoil(false)}
              className="text-slate-400 hover:text-slate-600 cursor-pointer p-0.5"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
            <div>
              <label className="text-[10px] font-medium text-slate-600 block mb-1">
                Equipment / Exchanger Name:
              </label>
              <input
                type="text"
                value={newCoilName}
                onChange={e => setNewCoilName(e.target.value)}
                placeholder="e.g. BFW Economizer Coil 2 or NG Pre-reformer"
                className="w-full px-2.5 py-1 bg-white border border-slate-300 rounded text-slate-800 text-xs focus:ring-1 focus:ring-[#0090d0] outline-none"
              />
            </div>

            <div>
              <label className="text-[10px] font-medium text-slate-600 block mb-1">
                Process Stream / Service:
              </label>
              <input
                type="text"
                value={newCoilStream}
                onChange={e => setNewCoilStream(e.target.value)}
                placeholder="e.g. Boiler Feed Water, LP Steam, Naphtha Feed"
                className="w-full px-2.5 py-1 bg-white border border-slate-300 rounded text-slate-800 text-xs focus:ring-1 focus:ring-[#0090d0] outline-none"
              />
            </div>

            <div>
              <label className="text-[10px] font-medium text-slate-600 block mb-1">
                Number of Shells / Modules:
              </label>
              <div className="flex items-center gap-1">
                {[1, 2, 3, 4, 5, 6].map(n => (
                  <button
                    key={n}
                    type="button"
                    onClick={() => setNewCoilShells(n)}
                    className={`px-2 py-0.5 rounded text-[11px] font-normal border transition-all cursor-pointer ${
                      newCoilShells === n
                        ? "bg-[#0090d0] text-white border-[#0090d0]"
                        : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                    }`}
                  >
                    {n}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="text-[10px] font-medium text-slate-600 block mb-1">
                Arrangement:
              </label>
              <div className="flex items-center gap-1.5">
                {(["Series", "Parallel"] as const).map(arr => (
                  <button
                    key={arr}
                    type="button"
                    onClick={() => setNewCoilArrangement(arr)}
                    className={`px-2.5 py-0.5 rounded text-[11px] font-normal border transition-all cursor-pointer ${
                      newCoilArrangement === arr
                        ? "bg-[#0090d0] text-white border-[#0090d0]"
                        : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                    }`}
                  >
                    {arr}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="flex items-center justify-end gap-2 mt-2.5 pt-2 border-t border-sky-200/60">
            <button
              type="button"
              onClick={() => setIsAddingCoil(false)}
              className="px-2.5 py-1 text-xs font-normal text-slate-600 hover:text-slate-800 cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleCreateConvectionCoil}
              disabled={!newCoilName.trim()}
              className="px-3 py-1 bg-[#0090d0] hover:bg-[#0080ba] disabled:opacity-50 text-white rounded text-xs font-normal flex items-center gap-1 shadow-2xs cursor-pointer"
            >
              <Check className="w-3.5 h-3.5" />
              <span>Add to Convection Train</span>
            </button>
          </div>
        </div>
      )}

      {/* Equipment List for Selected Section */}
      <div className="flex-1 overflow-y-auto p-2 space-y-1.5 custom-scrollbar bg-white">
        {itemsInCurrentZone.map((eq) => {
          const isBlue = eq.enabled;
          const isExchanger = 
            eq.id.includes("preheater") || 
            eq.id.includes("cooler") || 
            eq.id.includes("exchanger") ||
            eq.id.includes("conv_coil");
          const isCompressor = eq.id.includes("compressor") || eq.id.includes("fan");
          const isAdsorber = eq.id.includes("zno_adsorbers");
          const isSmr = eq.id === "smr_radiant_box";
          const isEditingThis = editingId === eq.id;

          return (
            <div 
              key={eq.id}
              className={`
                p-2 rounded-lg border transition-all duration-150 flex flex-col gap-1
                ${isBlue 
                  ? "border-sky-200 bg-sky-50/30" 
                  : "border-slate-200 bg-slate-50/50 opacity-60"
                }
              `}
            >
              {/* Main row: Name, Process Stream / Description, Edit Button, Toggle Switch */}
              <div className="flex items-start justify-between gap-2">
                <div className="flex-1 min-w-0">
                  {isEditingThis ? (
                    <div className="space-y-1.5 py-1">
                      <div>
                        <label className="text-[10px] font-medium text-slate-500 block mb-0.5">
                          Equipment Name / Tag:
                        </label>
                        <input
                          type="text"
                          value={editNameValue}
                          onChange={e => setEditNameValue(e.target.value)}
                          className="w-full px-2 py-1 bg-white border border-sky-300 rounded text-xs font-normal text-slate-800 outline-none focus:ring-1 focus:ring-[#0090d0]"
                        />
                      </div>
                      <div>
                        <label className="text-[10px] font-medium text-slate-500 block mb-0.5">
                          Process Stream / Description:
                        </label>
                        <input
                          type="text"
                          value={editStreamValue}
                          onChange={e => setEditStreamValue(e.target.value)}
                          className="w-full px-2 py-1 bg-white border border-sky-300 rounded text-[11px] font-normal text-slate-700 outline-none focus:ring-1 focus:ring-[#0090d0]"
                        />
                      </div>
                      <div className="flex items-center gap-1.5 pt-1">
                        <button
                          type="button"
                          onClick={() => saveEditing(eq.id)}
                          className="px-2.5 py-0.5 bg-[#0090d0] text-white rounded text-[11px] font-normal flex items-center gap-1 cursor-pointer"
                        >
                          <Check className="w-3 h-3" /> Save Name
                        </button>
                        <button
                          type="button"
                          onClick={() => setEditingId(null)}
                          className="px-2 py-0.5 text-slate-500 hover:text-slate-700 text-[11px] font-normal cursor-pointer"
                        >
                          Cancel
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div>
                      <div className="flex items-center gap-1.5 flex-wrap">
                        <span className={`text-[11px] font-medium leading-tight ${isBlue ? "text-slate-900" : "text-slate-500"}`}>
                          {eq.name}
                        </span>

                        {eq.required && (
                          <span className="text-[9px] font-normal text-amber-800 bg-amber-100 px-1.5 py-0.2 rounded">
                            Required
                          </span>
                        )}

                        {eq.isCustom && (
                          <span className="text-[9px] font-normal text-emerald-800 bg-emerald-100 px-1.5 py-0.2 rounded">
                            Custom Added
                          </span>
                        )}

                        {/* Inline edit pencil */}
                        <button
                          type="button"
                          onClick={() => startEditing(eq)}
                          title="Edit equipment name and process stream"
                          className="text-slate-400 hover:text-[#0090d0] p-0.5 rounded transition-colors cursor-pointer"
                        >
                          <Edit2 className="w-2.5 h-2.5" />
                        </button>

                        {/* Delete button for custom equipment */}
                        {eq.isCustom && onDeleteEquipment && (
                          <button
                            type="button"
                            onClick={() => onDeleteEquipment(eq.id)}
                            title="Remove this custom exchanger"
                            className="text-slate-400 hover:text-red-600 p-0.5 rounded transition-colors cursor-pointer"
                          >
                            <Trash2 className="w-2.5 h-2.5" />
                          </button>
                        )}
                      </div>

                      <p className="text-[10px] text-slate-500 mt-0.5 leading-snug truncate">
                        {eq.processStream ? `Stream: ${eq.processStream} • ` : ""}{eq.description}
                      </p>
                    </div>
                  )}
                </div>

                {/* Blue / White Toggle Switch */}
                <div className="shrink-0 flex items-center gap-1.5 pt-0.5">
                  <span className={`text-[10px] font-medium ${isBlue ? "text-[#0090d0]" : "text-slate-400"}`}>
                    {isBlue ? "YES" : "NO"}
                  </span>
                  <button
                    type="button"
                    role="switch"
                    aria-checked={isBlue}
                    onClick={() => onToggle(eq.id, !eq.enabled)}
                    className={`
                      relative inline-flex h-4 w-7 shrink-0 cursor-pointer rounded-full p-0.5
                      transition-colors duration-200 ease-in-out focus:outline-hidden
                      ${isBlue 
                        ? "bg-[#0090d0] border border-[#0090d0]" 
                        : "bg-white border-2 border-slate-300"
                      }
                    `}
                  >
                    <span className="sr-only">Toggle {eq.name}</span>
                    <span
                      className={`
                        pointer-events-none inline-block h-2.5 w-2.5 rounded-full transform transition duration-200 ease-in-out
                        ${isBlue 
                          ? "translate-x-3 bg-white shadow-2xs" 
                          : "translate-x-0 bg-slate-400"
                        }
                      `}
                    />
                  </button>
                </div>
              </div>

              {/* INLINE SUB-QUESTIONS: IF TOGGLED YES (BLUE) */}
              {isBlue && isExchanger && (
                <div className="mt-1 pt-1.5 border-t border-sky-100 grid grid-cols-2 gap-2 text-xs bg-white/95 p-1.5 rounded border border-sky-100">
                  <div>
                    <label className="text-[9px] font-medium text-slate-500 uppercase tracking-wider block mb-0.5">
                      No. of Exchangers / Shells:
                    </label>
                    <div className="flex items-center gap-1">
                      {[1, 2, 3, 4, 5, 6].map(n => (
                        <button
                          key={n}
                          type="button"
                          data-testid={`sub-exchanger-count-${n}`}
                          onClick={() => onUpdateSubOption(eq.id, "numExchangers", n)}
                          className={`px-1.5 py-0.5 rounded text-[10px] font-normal border transition-all cursor-pointer ${
                            (eq.numExchangers || (eq.id.includes("conv_coil") ? 1 : 2)) === n 
                              ? "bg-[#0090d0] text-white border-[#0090d0]" 
                              : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                          }`}
                        >
                          {n}
                        </button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <label className="text-[9px] font-medium text-slate-500 uppercase tracking-wider block mb-0.5">
                      Arrangement:
                    </label>
                    <div className="flex items-center gap-1">
                      {(["Series", "Parallel"] as const).map(arr => (
                        <button
                          key={arr}
                          type="button"
                          data-testid={`sub-exchanger-arr-${arr}`}
                          onClick={() => onUpdateSubOption(eq.id, "arrangement", arr)}
                          className={`px-2 py-0.5 rounded text-[10px] font-normal border transition-all cursor-pointer ${
                            (eq.arrangement || "Series") === arr 
                              ? "bg-[#0090d0] text-white border-[#0090d0]" 
                              : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                          }`}
                        >
                          {arr}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {/* Sub-questions for Compressor / Fans */}
              {isBlue && isCompressor && (
                <div className="mt-1 pt-1.5 border-t border-sky-100 grid grid-cols-2 gap-2 text-xs bg-white/95 p-1.5 rounded border border-sky-100">
                  <div>
                    <label className="text-[9px] font-medium text-slate-500 uppercase tracking-wider block mb-0.5">
                      Compression Stages:
                    </label>
                    <div className="flex items-center gap-1">
                      {[1, 2, 3].map(st => (
                        <button
                          key={st}
                          type="button"
                          onClick={() => onUpdateSubOption(eq.id, "stages", st)}
                          className={`px-2 py-0.5 rounded text-[10px] font-normal border transition-all cursor-pointer ${
                            (eq.stages || 2) === st 
                              ? "bg-[#0090d0] text-white border-[#0090d0]" 
                              : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                          }`}
                        >
                          {st} Stg
                        </button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <label className="text-[9px] font-medium text-slate-500 uppercase tracking-wider block mb-0.5">
                      Driver Machine:
                    </label>
                    <div className="flex items-center gap-1">
                      {(["Electric Motor", "Steam Turbine"] as const).map(d => (
                        <button
                          key={d}
                          type="button"
                          onClick={() => onUpdateSubOption(eq.id, "driverType", d)}
                          className={`px-2 py-0.5 rounded text-[10px] font-normal border transition-all cursor-pointer ${
                            (eq.driverType || "Electric Motor") === d 
                              ? "bg-[#0090d0] text-white border-[#0090d0]" 
                              : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                          }`}
                        >
                          {d.replace("Electric ", "").replace("Steam ", "")}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {/* Sub-questions for ZnO Adsorbers */}
              {isBlue && isAdsorber && (
                <div className="mt-1 pt-1.5 border-t border-sky-100 grid grid-cols-2 gap-2 text-xs bg-white/95 p-1.5 rounded border border-sky-100">
                  <div>
                    <label className="text-[9px] font-medium text-slate-500 uppercase tracking-wider block mb-0.5">
                      Bed Configuration:
                    </label>
                    <div className="flex items-center gap-1">
                      {(["Lead-Lag Dual Bed", "Single Bed"] as const).map(arr => (
                        <button
                          key={arr}
                          type="button"
                          onClick={() => onUpdateSubOption(eq.id, "adsorberArrangement", arr)}
                          className={`px-2 py-0.5 rounded text-[10px] font-normal border transition-all cursor-pointer ${
                            (eq.adsorberArrangement || "Lead-Lag Dual Bed") === arr 
                              ? "bg-[#0090d0] text-white border-[#0090d0]" 
                              : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                          }`}
                        >
                          {arr.replace(" Dual Bed", "")}
                        </button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <label className="text-[9px] font-medium text-slate-500 uppercase tracking-wider block mb-0.5">
                      Sulfur Specification:
                    </label>
                    <span className="font-mono text-[10px] font-normal text-emerald-600">
                      &lt; 0.05 ppm wt (Polished)
                    </span>
                  </div>
                </div>
              )}

              {/* Sub-questions for SMR Furnace */}
              {isBlue && isSmr && (
                <div className="mt-1 pt-1.5 border-t border-sky-100 grid grid-cols-2 gap-2 text-xs bg-white/95 p-1.5 rounded border border-sky-100">
                  <div>
                    <label className="text-[9px] font-medium text-slate-500 uppercase tracking-wider block mb-0.5">
                      Burner Arrangement:
                    </label>
                    <div className="flex items-center gap-1">
                      {(["Top-Fired", "Side-Fired"] as const).map(f => (
                        <button
                          key={f}
                          type="button"
                          onClick={() => onUpdateSubOption(eq.id, "firingType", f)}
                          className={`px-2 py-0.5 rounded text-[10px] font-normal border transition-all cursor-pointer ${
                            (eq.firingType || "Top-Fired") === f 
                              ? "bg-[#0090d0] text-white border-[#0090d0]" 
                              : "bg-white text-slate-700 border-slate-200 hover:bg-slate-50"
                          }`}
                        >
                          {f}
                        </button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <label className="text-[9px] font-medium text-slate-500 uppercase tracking-wider block mb-0.5">
                      Catalyst Tubes:
                    </label>
                    <span className="font-normal text-[#0090d0] text-[10px]">480 Vertical Catalyst Tubes</span>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Clean 1-Line Info Footer */}
      <div className="px-3.5 py-1.5 border-t border-slate-200 bg-slate-50 flex items-center justify-between text-[10px] text-slate-400 shrink-0">
        <div className="flex items-center gap-1.5">
          <Info className="w-3 h-3 text-[#0090d0]" />
          <span className="font-normal">Customizable equipment tags &amp; flexible convection coil banks.</span>
        </div>
        <span className="font-medium text-slate-500">Section {currentZoneMeta.num} of 6</span>
      </div>
    </div>
  );
};
